### ISSUE TITLE
Errors in `Finally` block

### ISSUE THREAD

**Issue by wqweto** [OlimilO1402/Err_CorrectErrorHandling#1]
FYI, currently any error which occurs in the `Finally` block would be caught to the the previous error handling `Catch` block which is not an expected behavior and not what happens in other languages (e.g. Java, C#).

In this regard you might consider educating the masses to use `On Error GoTo 0` or `On Error Resume Next` in the beginning of  the `Finally` block to not re-enter `Catch` block when things go awry in the terminating `Finally` block.

**Comment by OlimilO1402** [comment]
Hi Vladimir, thanks for reporting the issue. Good point, I would update my "tutorial" asap. Do you have or know a currenct case, where you or someone else ran into problems?

**Comment by wqweto** [comment]
I've been bitten by this unexpected self-inflicted behavior numerous times, often resulting in my app hanging in an infinite loop.

Other languages effectively set `On Error GoTo 0` in the `Finally` block so the errors in the terminating block (most often invalid use of uninitialized null references) can bubble up to the caller procedure but in VB one can choose to silence everything that pops up with `On Error Resume Next` which is not the better approach but still possible.

**Comment by OlimilO1402** [comment]
I tried digging into the problem and now i must say, I am sorry, I can not share your idea at the moment.
I did not know the code would jump back to "Catch" when the error occurs in "Finally", but I do not see any infinite loop with Try-Catch-Finally, and maybe "On Error GoTo 0" can make it even worse.
Maybe an example could help to clear things up. Consider the following code in a form
```vba
Private Function MyFunction() As Boolean
Try: On Error GoTo Catch
    Dim F As File: 'Set F = New File
    'F.OpenFile
    MyFunction=True
    GoTo Finally
Catch:
    MsgBox "MyFunction1 Catch: " & Err.Number & " " & Err.Description
Finally: 'On Error GoTo 0
    'if the error occurs only in the Finally-block,
    'the app will jump back to the Catch-block, shows the error
    'then runs into the Finally-block again, and then does *not* crash
    'only if the Caller has got a error-handling mechanism too,
    'otherwise it will crash in any circumstance
    'if the finally-block starts with "On Error GoTo 0" the only thing what it does
    'it never runs into the Catch-block and you get no chance to get a decent Error-information.
    F.CloseFile
End Function

Private Sub Command1_Click()
    'Without any errorhandling in the caller, the app will crash!!!
Try: 'On Error Resume Next
    Dim i As Long
    i = MyFunction
End Sub
```
The only thing what can safe the apps life is an error handling mechanism in the Caller.
The tiny code above, you will also find in the new folder Test1 in the repo

**Comment by wqweto** [comment]
Well, for an infinite loop to happen in error handling one has to use `Resume [Label]` of some sort in the `Catch` block.

Often using `GoTo Label` instead of `Resume Label` actually **prevents** infinite loops because the repeat error is raised to the caller with `GoTo` while the same repeat error would again jump in `Catch` if `Resume` were used and this **might** begin looping between `Resume [Label]` and `Catch`.

Also note that the way you structured your sample above, any error handler installed in `Finally` section (e.g. `On Error Resume Next`) would be **ignored** if `Finally` block is reached by fall-through from `Catch` section. So if OERN is required in `Fianlly` in your example you have to add in `Catch` section one final `Resume Finally` so that `On Error ...` to work in `Finally` section when termination comes from an error.

**Comment by OlimilO1402** [comment]
OK I see! In case creating an object fails, then often the error occurs twice: in Try- and in Finally-block, by trying to free handles.
With a "Resume Finally" at the end of the first Catch-block we are able to install a second errhandler in the same function in the Finally-block. The second errhandler may even be rudimentary just a simple "On Error GoTo End_Try" will do it.
Thanks for the idea I will update the tut. 
The complete package of Try-Catch-Finally-End_Try now is:
```vba
Private Sub Command4_Click()
    'Error will occur twice, in Try- and in Finally-block
Try: On Error GoTo Catch
    Dim PFN As PathFileName
    'Set PFN = New PathFileName 'Oopps we forgot to create the object
    PFN.OOpen ' now this will lead to an error in Try
    GoTo Finally
Catch:
    ErrHandler "Command4_Click", "Catch"
    Resume Finally
Finally: On Error GoTo End_Try
    PFN.CClose 'now this will lead to an error too, now we are in the Finally-block, we straight go to End_Try
End_Try:
End Sub
```

**Comment by OlimilO1402** [comment]
oh in every case we need a second Catch, otherwise we get no error-message at all, if the error occurs only in Finally
There must be a feasible way in any circumstances . . . the following cases:
* either no error message if everything is OK, 
* an error-message if error occurs only once in Try
* an error-message if error occurs twice in Try and Finally
* an error-message if error occurs only in Finally
The complete package of Try-Catch-Finally-End_Try then must be:
```vba
Try: On Error GoTo Catch
    'some error-prone code here
    GoTo Finally
Catch:
    ErrHandler "Command_Click", "Catch"
    Resume Finally
Finally: On Error GoTo Catch2
    'another possible error here
    GoTo End_Try
Catch2:
    ErrHandler "Command_Click", "Catch2"
End_Try:
```

**Comment by OlimilO1402** [comment]
OK, update, please have a short look :-)

**Comment by wqweto** [comment]
LGTM

It is a bit verbose but quite exaustive. 

The other more terse options is to add `Resume Finally` statement only and leave it to implementor to decide how to handle errors in `Finally` section incl. second `Catch2` handler or just leave it with no error handler i.e. propagate errors in `Finally` section to caller.
